const MAJOR_KEYS=['C','G','D','A','E','B','F♯','D♭','A♭','E♭','B♭','F'];
const MINOR_KEYS=['A','E','B','F♯','C♯','G♯','D♯','B♭','F','C','G','D'];
const SCALES={C:['C','D','E','F','G','A','B'],G:['G','A','B','C','D','E','F♯'],D:['D','E','F♯','G','A','B','C♯'],A:['A','B','C♯','D','E','F♯','G♯'],E:['E','F♯','G♯','A','B','C♯','D♯'],B:['B','C♯','D♯','E','F♯','G♯','A♯'],'F♯':['F♯','G♯','A♯','B','C♯','D♯','E♯'],'D♭':['D♭','E♭','F','G♭','A♭','B♭','C'],'A♭':['A♭','B♭','C','D♭','E♭','F','G'],'E♭':['E♭','F','G','A♭','B♭','C','D'],'B♭':['B♭','C','D','E♭','F','G','A'],'F':['F','G','A','B♭','C','D','E']};
const SIGNATURES=['Sin alteraciones','1 sostenido','2 sostenidos','3 sostenidos','4 sostenidos','5 sostenidos','6 sostenidos','5 bemoles','4 bemoles','3 bemoles','2 bemoles','1 bemol'];
const PATTERNS={major:{roman:['I','ii','iii','IV','V','vi','vii°'],quality:['Mayor','menor','menor','Mayor','Mayor','menor','disminuido'],suffix:['','m','m','','','m','°']},minor:{roman:['i','ii°','III','iv','v','VI','VII'],quality:['menor','disminuido','Mayor','menor','menor','Mayor','Mayor'],suffix:['m','°','','m','m','','']}};
const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
const state={key:MAJOR_KEYS.includes(params.get('key'))?params.get('key'):'C',mode:params.get('mode')==='minor'?'minor':'major',progression:[]};
const indexOfKey=()=>MAJOR_KEYS.indexOf(state.key);
const root=()=>state.mode==='major'?state.key:MINOR_KEYS[indexOfKey()];
const notePc=note=>({C:0,D:2,E:4,F:5,G:7,A:9,B:11}[note[0]]+(note.includes('♯')?1:note.includes('♭')?-1:0)+12)%12;
function parallelKey(mode){const names=mode==='major'?MAJOR_KEYS:MINOR_KEYS,tonic=root(),exact=names.indexOf(tonic);const index=exact>=0?exact:names.findIndex(note=>notePc(note)===notePc(tonic));return MAJOR_KEYS[index]}
const scale=()=>{const notes=SCALES[state.key];return state.mode==='major'?notes:[...notes.slice(5),...notes.slice(0,5)]};
const chord=i=>{const p=PATTERNS[state.mode];return{root:scale()[i],name:scale()[i]+p.suffix[i],roman:p.roman[i],quality:p.quality[i]}};
const nameFor=(i,mode=state.mode)=>mode==='major'?MAJOR_KEYS[(i+12)%12]:MINOR_KEYS[(i+12)%12]+'m';
const LATIN_NOTE_NAMES={C:'Do',D:'Re',E:'Mi',F:'Fa',G:'Sol',A:'La',B:'Si'};
function latinNote(note){return LATIN_NOTE_NAMES[note[0]]+note.slice(1)}
function tooltipDetails(key,mode){const i=MAJOR_KEYS.indexOf(key),minor=MINOR_KEYS[i],tonic=mode==='major'?key:minor,parallel=mode==='major'?minor+'m':key,neighbors=mode==='major'?[MAJOR_KEYS[(i+11)%12],MAJOR_KEYS[(i+1)%12]]:[MINOR_KEYS[(i+11)%12]+'m',MINOR_KEYS[(i+1)%12]+'m'],count=i<=6?i:12-i,accidental=i<=6?'♯':'♭',order=i<=6?['F','C','G','D','A','E']:['B','E','A','D','G'],altered=order.slice(0,count).map(note=>note+accidental),signature=count?`${count} ${i<=6?(count===1?'sostenido':'sostenidos'):(count===1?'bemol':'bemoles')} (${altered.join(', ')})`:'sin alteraciones',notes=mode==='major'?SCALES[key]:[...SCALES[key].slice(5),...SCALES[key].slice(0,5)],chords=mode==='major'?[notes[0],notes[3],notes[4]]:[notes[0]+'m',notes[3]+'m',notes[4]+'m'],degrees=mode==='major'?'I · IV · V':'i · iv · v',dominant=mode==='minor'?` · con V mayor: ${notes[4]}`:'',equivalent=key==='F♯'?'Equivale a G♭ mayor / E♭ menor (6 bemoles)':'';return{title:mode==='major'?`${key} mayor · ${latinNote(key)} mayor`:`${tonic}m · ${latinNote(tonic)} menor`,signature:`Armadura: ${signature}`,relations:`Relativa: ${parallel} · Vecinas: ${neighbors[0]} y ${neighbors[1]}`,chords:`Acordes principales: ${chords.join(' · ')} (${degrees})${dominant}`,equivalent}}
const fullName=()=>root()+(state.mode==='major'?' mayor':' menor natural');
function updateLinks(){document.querySelectorAll('[data-page-link]').forEach(a=>{const target=new URL(a.dataset.pageLink,location.href);target.searchParams.set('key',state.key);target.searchParams.set('mode',state.mode);a.href=target});const url=new URL(location.href);url.searchParams.set('key',state.key);url.searchParams.set('mode',state.mode);history.replaceState(null,'',url)}
function fillSelectors(){const keySelect=$('keySelect'),modeSelect=$('modeSelect');if(!keySelect||!modeSelect)return;keySelect.innerHTML=MAJOR_KEYS.map((k,i)=>`<option value="${k}">${nameFor(i)} · ${latinNote(state.mode==='major'?k:MINOR_KEYS[i])} ${state.mode==='major'?'mayor':'menor'}</option>`).join('');keySelect.value=state.key;modeSelect.value=state.mode}
function setSelection(key,mode){state.key=key;state.mode=mode;state.progression=[];stopAudio();render()}
function selectEvents(){const keySelect=$('keySelect'),modeSelect=$('modeSelect');if(!keySelect)return;keySelect.addEventListener('change',e=>setSelection(e.target.value,state.mode));modeSelect.addEventListener('change',e=>setSelection(parallelKey(e.target.value),e.target.value));$('relativeKey').addEventListener('click',()=>setSelection(state.key,state.mode==='major'?'minor':'major'))}
function point(radius,i){const angle=(i*30-90)*Math.PI/180;return{x:280+radius*Math.cos(angle),y:280+radius*Math.sin(angle)}}
function pathSector(inner,outer,index){const a1=(index*30-105)*Math.PI/180,a2=(index*30-75)*Math.PI/180;const p=(r,a)=>`${(280+r*Math.cos(a)).toFixed(2)} ${(280+r*Math.sin(a)).toFixed(2)}`;return `M ${p(outer,a1)} A ${outer} ${outer} 0 0 1 ${p(outer,a2)} L ${p(inner,a2)} A ${inner} ${inner} 0 0 0 ${p(inner,a1)} Z`}
function animateCircleGeometry(svg,targetIndex,targetMode){if(svg._geometryFrame)cancelAnimationFrame(svg._geometryFrame);const targetMajor=targetMode==='major'?1:0,fromIndex=Number(svg.dataset.currentIndex??targetIndex),fromMajor=Number(svg.dataset.currentMajor??targetMajor),delta=((targetIndex-fromIndex+18)%12)-6,reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const draw=(index,major)=>{const activeR=126+65*major,relativeR=191-65*major,a=point(activeR,index),r=point(relativeR,index),prev=point(activeR,index-1),next=point(activeR,index+1);svg.querySelector('.sector').setAttribute('d',pathSector(89+69*major,158+66*major,index));const links=svg.querySelectorAll('.link-neighbor');[[prev,a],[a,next]].forEach(([from,to],i)=>{links[i].setAttribute('x1',from.x);links[i].setAttribute('y1',from.y);links[i].setAttribute('x2',to.x);links[i].setAttribute('y2',to.y)});const relativeLine=svg.querySelector('.link-relative');relativeLine.setAttribute('x1',a.x);relativeLine.setAttribute('y1',a.y);relativeLine.setAttribute('x2',r.x);relativeLine.setAttribute('y2',r.y);svg.dataset.currentIndex=index;svg.dataset.currentMajor=major};if(reduced){draw(targetIndex,targetMajor);return}const start=performance.now(),duration=420;function tick(now){const t=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-t,3);draw(fromIndex+delta*ease,fromMajor+(targetMajor-fromMajor)*ease);if(t<1)svg._geometryFrame=requestAnimationFrame(tick);else svg._geometryFrame=null}svg._geometryFrame=requestAnimationFrame(tick)}
function renderCircle(){const svg=$('circle');if(!svg)return;const selected=indexOfKey(),isMajor=state.mode==='major',activeR=isMajor?191:126,relativeR=isMajor?126:191,a=point(activeR,selected),r=point(relativeR,selected),prev=point(activeR,(selected+11)%12),next=point(activeR,(selected+1)%12);
  if(svg.dataset.built==='true'){animateCircleGeometry(svg,selected,state.mode);svg.querySelectorAll('.node').forEach(node=>{const i=MAJOR_KEYS.indexOf(node.dataset.key),mode=node.dataset.mode;node.classList.toggle('active',i===selected&&mode===state.mode);node.classList.toggle('relative',i===selected&&mode!==state.mode);node.classList.toggle('neighbor',(i===(selected+11)%12||i===(selected+1)%12)&&mode===state.mode)});svg.querySelector('.center-big').textContent=root();svg.querySelector('.center-small').textContent=isMajor?'MAYOR':'MENOR';return}
  let html=`<circle cx="280" cy="280" r="224" class="orbit"/><circle cx="280" cy="280" r="158" class="orbit"/><circle cx="280" cy="280" r="89" class="orbit dashed"/><path class="sector" d="${pathSector(isMajor?158:89,isMajor?224:158,selected)}"/><line class="link-neighbor" x1="${prev.x}" y1="${prev.y}" x2="${a.x}" y2="${a.y}"/><line class="link-neighbor" x1="${a.x}" y1="${a.y}" x2="${next.x}" y2="${next.y}"/><line class="link-relative" x1="${a.x}" y1="${a.y}" x2="${r.x}" y2="${r.y}"/><circle class="center-disc" cx="280" cy="280" r="85"/>`;
  MAJOR_KEYS.forEach((key,i)=>{for(const mode of ['major','minor']){const p=point(mode==='major'?191:126,i),active=i===selected&&mode===state.mode,relative=i===selected&&mode!==state.mode,neighbor=(i===(selected+11)%12||i===(selected+1)%12)&&mode===state.mode,label=mode==='major'?key:MINOR_KEYS[i]+'m',order=i*2+(mode==='minor'?1:0),detail=mode==='major'?`${key} mayor · relativa menor ${MINOR_KEYS[i]}m`:`${MINOR_KEYS[i]} menor natural · relativa mayor ${key}`,description=`${detail} · ${SIGNATURES[i]}`;html+=`<g class="node ${mode} ${active?'active':''} ${relative?'relative':''} ${neighbor?'neighbor':''}" style="--node-order:${order}" data-key="${key}" data-mode="${mode}" data-description="${description}" role="button" tabindex="0" aria-describedby="circleTooltip" aria-label="${label}: ${description}. Seleccionar tonalidad"><circle cx="${p.x}" cy="${p.y}" r="${mode==='major'?26:23}" fill="#263745" stroke="#445868" stroke-width="1.2"/><text x="${p.x}" y="${p.y+1}">${label}</text></g>`}})
  html+=`<text x="280" y="250" class="center-caption">TONALIDAD</text><text x="280" y="298" class="center-big">${root()}</text><text x="280" y="320" class="center-small">${isMajor?'MAYOR':'MENOR'}</text>`;svg.innerHTML=html;svg.dataset.built='true';svg.dataset.currentIndex=selected;svg.dataset.currentMajor=isMajor?1:0}
function renderScaleAndFacts(){if(!$('scaleNotes'))return;const i=indexOfKey(),relative=state.mode==='major'?MINOR_KEYS[i]+'m':MAJOR_KEYS[i],left=nameFor((i+11)%12),right=nameFor((i+1)%12);$('selectedName').textContent=fullName();$('selectedLatin').textContent=`${latinNote(root())} ${state.mode==='major'?'mayor':'menor'}`;$('signature').textContent=SIGNATURES[i];$('relative').textContent=relative;$('relativeKey').textContent=`Ir a relativa ${relative}`;$('neighborLeft').textContent=left;$('neighborRight').textContent=right;$('scaleNotes').innerHTML=scale().map((n,j)=>`<span class="note ${j===0?'root':''}"><strong>${n}</strong><small>${latinNote(n)}</small></span>`).join('');$('selectionDescription').textContent=`${fullName()}: ${SIGNATURES[i].toLowerCase()}. Su relativa es ${relative}.`;$('chordGrid').innerHTML=Array.from({length:7},(_,j)=>{const c=chord(j);return `<div class="chord-info"><span class="roman">${c.roman}</span><span><strong>${c.name}</strong><small>${c.quality}</small></span></div>`}).join('')}
function renderComposer(){if(!$('composerChords'))return;$('composerKey').textContent=fullName();$('composerSignature').textContent=SIGNATURES[indexOfKey()];$('composerChords').innerHTML=Array.from({length:7},(_,i)=>{const c=chord(i);return `<button type="button" class="chord-button" data-degree="${i}" aria-label="Añadir ${c.name}, grado ${c.roman}"><span class="roman">${c.roman}</span><span><strong>${c.name}</strong><small>${c.quality}</small></span><span class="plus" aria-hidden="true">+</span></button>`}).join('');$('presetName').textContent=state.mode==='major'?'I – V – vi – IV':'i – VI – III – VII';renderProgression()}
function renderProgression(){if(!$('progressGrid'))return;$('progressGrid').innerHTML=Array.from({length:8},(_,i)=>{const c=state.progression[i];return `<button type="button" class="measure ${c?'filled':''}" data-slot="${i}" aria-label="${c?`Quitar ${c.name} del compás ${i+1}`:`Compás ${i+1} vacío`}"><span class="number">${String(i+1).padStart(2,'0')}</span>${c?`<strong>${c.name}</strong><span class="roman">${c.roman}</span>`:'<span>—</span>'}</button>`}).join('');$('play').disabled=!state.progression.length;$('progressHelp').textContent=state.progression.length?`${state.progression.length} ${state.progression.length===1?'acorde':'acordes'} en la secuencia. Toca un compás para quitarlo.`:'Elige un acorde de la lista para comenzar.'}
let audioContext=null,masterGain=null,playTimer=null;
function stopAudio(){if(playTimer)clearTimeout(playTimer);playTimer=null;if(masterGain&&audioContext){masterGain.gain.setTargetAtTime(0,audioContext.currentTime,.018);masterGain=null}if($('play'))$('play').textContent='▶ Escuchar'}
function frequency(note){const semitones={C:0,D:2,E:4,F:5,G:7,A:9,B:11};return 130.8128*Math.pow(2,(semitones[note[0]]+(note.includes('♯')?1:note.includes('♭')?-1:0))/12)}
function sound(c,time){const intervals=c.quality==='menor'?[0,3,7]:c.quality==='disminuido'?[0,3,6]:[0,4,7];intervals.forEach(n=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='triangle';osc.frequency.value=frequency(c.root)*Math.pow(2,n/12);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(.09,time+.025);gain.gain.exponentialRampToValueAtTime(.001,time+.85);osc.connect(gain).connect(masterGain);osc.start(time);osc.stop(time+.9)})}
function composerEvents(){$('composerChords').addEventListener('click',e=>{const target=e.target.closest('[data-degree]');if(target&&state.progression.length<8){state.progression.push(chord(Number(target.dataset.degree)));renderProgression()}});$('progressGrid').addEventListener('click',e=>{const target=e.target.closest('[data-slot]');if(target&&state.progression[Number(target.dataset.slot)]){state.progression.splice(Number(target.dataset.slot),1);stopAudio();renderProgression()}});$('clear').addEventListener('click',()=>{state.progression=[];stopAudio();renderProgression()});$('preset').addEventListener('click',()=>{state.progression=(state.mode==='major'?[0,4,5,3]:[0,5,2,6]).map(chord);stopAudio();renderProgression()});$('play').addEventListener('click',async()=>{if(playTimer){stopAudio();return}try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();masterGain=audioContext.createGain();masterGain.connect(audioContext.destination);$('play').textContent='■ Detener';state.progression.forEach((c,i)=>sound(c,audioContext.currentTime+i*.78));playTimer=setTimeout(stopAudio,state.progression.length*780+250)}catch{$('progressHelp').textContent='Este navegador no pudo reproducir el audio.'}})}
function render(){fillSelectors();updateLinks();renderCircle();renderScaleAndFacts();renderComposer()}
function showCircleTooltip(node,x,y){const tooltip=$('circleTooltip'),stage=document.querySelector('.circle-stage');if(!node||!tooltip||!stage)return;const bounds=stage.getBoundingClientRect(),noteId=`${node.dataset.key}-${node.dataset.mode}`;if(tooltip.dataset.note!==noteId){const details=tooltipDetails(node.dataset.key,node.dataset.mode);tooltip.innerHTML=`<strong>${details.title}</strong><span>${details.signature}</span><span>${details.relations}</span><span>${details.chords}</span>${details.equivalent?`<small>${details.equivalent}</small>`:''}`;tooltip.dataset.note=noteId}tooltip.style.left=`${Math.max(8,Math.min(bounds.width-tooltip.offsetWidth-8,x+14))}px`;tooltip.style.top=`${Math.max(8,Math.min(bounds.height-tooltip.offsetHeight-8,y+14))}px`;tooltip.classList.add('visible');tooltip.setAttribute('aria-hidden','false')}
function hideCircleTooltip(){const tooltip=$('circleTooltip');if(!tooltip)return;tooltip.classList.remove('visible');tooltip.setAttribute('aria-hidden','true')}
selectEvents();if($('circle')){const circle=$('circle'),stage=document.querySelector('.circle-stage'),pointerPosition=e=>{const bounds=stage.getBoundingClientRect();return{x:e.clientX-bounds.left,y:e.clientY-bounds.top}},showForPointer=e=>{const node=e.target.closest('[data-key]');if(node){const p=pointerPosition(e);showCircleTooltip(node,p.x,p.y)}};circle.addEventListener('mouseover',showForPointer);circle.addEventListener('mousemove',showForPointer);circle.addEventListener('pointerover',showForPointer);circle.addEventListener('pointermove',showForPointer);circle.addEventListener('pointerleave',hideCircleTooltip);circle.addEventListener('focusin',e=>{const node=e.target.closest('[data-key]');if(node){const box=node.getBoundingClientRect(),bounds=stage.getBoundingClientRect();showCircleTooltip(node,box.left+box.width/2-bounds.left,box.top+box.height/2-bounds.top)}});circle.addEventListener('focusout',e=>{if(!e.relatedTarget?.closest?.('[data-key]'))hideCircleTooltip()});circle.addEventListener('click',e=>{const node=e.target.closest('[data-key]');if(node)setSelection(node.dataset.key,node.dataset.mode)});circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const node=e.target.closest('[data-key]');if(node){e.preventDefault();setSelection(node.dataset.key,node.dataset.mode)}}})}if($('composerChords'))composerEvents();render();
