(()=>{
  const ACTIVE='circle-guided-tour-active-v1',INDEX='circle-guided-tour-index-v1',CLEAN='circle-guided-tour-clean-v1',DONE='circle-guided-tour-completed-v1';
  const steps=[
    {page:'index.html',target:'.node[data-key="G"][data-mode="major"]',title:'1. Explora una quinta vecina',copy:'En el círculo, pulsa G. Está a una quinta de C: observa cómo cambia la tonalidad y qué notas comparte con las cercanas.',action:'click',do:'Pulsa el nodo G del círculo.'},
    {page:'index.html',target:'#relativeKey',title:'2. Cambia al centro relativo',copy:'Ahora prueba la relativa menor. Comparte armadura con G mayor, pero el centro tonal pasa a ser otro.',action:'click',do:'Pulsa «Ir a relativa».'},
    {page:'index.html',target:'.nav a[href*="progresiones.html"]',title:'3. Pasa de explorar a crear',copy:'El círculo sirve para orientarte; el taller transforma esa elección en acordes que puedes ordenar y escuchar.',action:'click',do:'Abre «Crear» en el menú.'},
    {page:'progresiones.html',target:'#keySelect',title:'4. Elige la tonalidad del ejercicio',copy:'La tonalidad determina las notas disponibles. Al cambiarla, los grados de una secuencia se conservan y se transportan.',action:'change',do:'Cambia la tonalidad en este selector.'},
    {page:'progresiones.html',target:'#modeSelect',title:'5. Compara mayor y menor',copy:'El modo cambia el color y los acordes. En esta app, pasar de modo mantiene la relación paralela; no es lo mismo que saltar a la relativa.',action:'change',do:'Prueba el otro modo.'},
    {page:'progresiones.html',target:'#composerChords [data-add="0"]',title:'6. Añade el acorde de casa',copy:'El primer grado funciona como centro de reposo. Las opciones muestran tanto el nombre del acorde como su grado romano.',action:'click',do:'Pulsa «+» en el primer acorde.'},
    {page:'progresiones.html',target:'#composerChords [data-add="4"]',title:'7. Añade un acorde con movimiento',copy:'El quinto grado suele crear tensión que puede volver a la tónica. Escucha la diferencia entre estabilidad y movimiento.',action:'click',do:'Pulsa «+» en el quinto grado.'},
    {page:'progresiones.html',target:'#play',title:'8. Escucha lo que construiste',copy:'No busques una respuesta correcta: nota cuál acorde se siente como hogar y qué pasa cuando el otro acorde lo desplaza.',action:'click',do:'Pulsa «Escuchar»; luego usa Siguiente para continuar.'},
    {page:'progresiones.html',target:'#play',title:'9. Detén la escucha cuando quieras',copy:'Puedes dejar que termine o detenerla ahora. Si el bucle sigue sonando, Siguiente lo detendrá antes de pasar al guardado.',action:'stop',do:'Pulsa «Detener» o Siguiente.'},
    {page:'progresiones.html',target:'#saveIdea',title:'10. Guarda una versión, no solo la sesión',copy:'Escribe un nombre en el campo justo encima —por ejemplo, «Verso en Re menor»— y guarda. Así creas una copia independiente con acordes, tempo y ritmo.',action:'click',do:'Pulsa «Guardar idea».'},
    {page:'progresiones.html',target:'.nav a[href="./ideas.html"]',title:'11. Abre tu biblioteca',copy:'Las ideas con nombre viven en una pestaña propia. Desde allí podrás volver al informe o retomar una versión sin reconstruirla.',action:'click',do:'Abre «Ideas» en el menú.'},
    {page:'ideas.html',target:'#ideaLibrary',title:'12. Lee el informe y retoma',copy:'Cada tarjeta resume tonalidad, acordes y grados, duración, tempo, ritmo y disposición. «Retomar esta idea» la carga de nuevo en Crear.',action:'manual',do:'Cuando termines de revisar, pulsa Finalizar.'}
  ];
  const storage={get(key){try{return sessionStorage.getItem(key)}catch{return null}},set(key,value){try{sessionStorage.setItem(key,String(value))}catch{}},remove(key){try{sessionStorage.removeItem(key)}catch{}}};
  let layer,focus,tip,index=0,frame=0;
  const currentPage=()=>location.pathname.split('/').pop()||'index.html';
  const currentStep=()=>steps[index];
  const active=()=>storage.get(ACTIVE)==='1';
  function routeTo(page){const params=new URLSearchParams(location.search),query=new URLSearchParams();if(['index.html','progresiones.html'].includes(page)){query.set('key',params.get('key')||'C');query.set('mode',params.get('mode')||'major')}if(page==='progresiones.html'&&active()&&Number(storage.get(INDEX))===3&&storage.get(CLEAN)!=='1'){query.set('tour','1');storage.set(CLEAN,'1')}location.assign(`./${page}${query.size?`?${query}`:''}`)}
  function buildLayer(){if(layer)return;layer=document.createElement('div');layer.className='guided-tour-layer';layer.hidden=true;layer.innerHTML='<div class="guided-tour-focus" aria-hidden="true"></div><section class="guided-tour-tip" role="dialog" aria-modal="true" aria-labelledby="guidedTourTitle" aria-describedby="guidedTourCopy"><div class="guided-tour-top"><span class="guided-tour-count"></span><button type="button" class="guided-tour-close" aria-label="Salir del recorrido">×</button></div><h2 id="guidedTourTitle"></h2><p id="guidedTourCopy" class="guided-tour-copy"></p><span class="guided-tour-do"></span><div class="guided-tour-controls"><button type="button" class="button guided-tour-exit">Salir</button><button type="button" class="button guided-tour-back">Anterior</button><button type="button" class="button primary guided-tour-next">Siguiente</button></div></section>';
    focus=layer.querySelector('.guided-tour-focus');tip=layer.querySelector('.guided-tour-tip');tip.querySelector('.guided-tour-close').addEventListener('click',stop);tip.querySelector('.guided-tour-exit').addEventListener('click',stop);tip.querySelector('.guided-tour-back').addEventListener('click',()=>advance(-1));tip.querySelector('.guided-tour-next').addEventListener('click',()=>advance(1));document.body.append(layer)}
  function setIndex(next){index=next;storage.set(INDEX,index);if(index<0){stop();return}if(index>=steps.length){finish();return}const step=currentStep();if(currentPage()!==step.page){routeTo(step.page);return}showStep()}
  function advance(direction){const next=index+direction;if(next<0)return;if(index===8&&direction>0){const play=document.getElementById('play');if(play?.textContent.includes('Detener'))play.click()}setIndex(next)}
  function stop(){storage.remove(ACTIVE);storage.remove(INDEX);storage.remove(CLEAN);if(layer)layer.hidden=true;window.removeEventListener('scroll',schedulePosition)}
  function finish(){storage.remove(ACTIVE);storage.remove(INDEX);storage.remove(CLEAN);if(layer)layer.hidden=true;window.removeEventListener('scroll',schedulePosition);if(currentPage()!=='tutorial.html'){storage.set(DONE,'1');location.assign('./tutorial.html');return}showCompletionNotice()}
  function showCompletionNotice(){storage.remove(DONE);const notice=document.createElement('p');notice.className='guided-tour-complete';notice.setAttribute('role','status');notice.textContent='Recorrido completado. Volviste a Aprender; puedes repetirlo o seguir explorando.';document.body.append(notice);setTimeout(()=>notice.remove(),7000)}
  function schedulePosition(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;position()})}
  function position(){if(!active()||!layer||layer.hidden)return;const step=currentStep();if(!step||currentPage()!==step.page)return;const target=document.querySelector(step.target);if(!target)return;const rect=target.getBoundingClientRect(),pad=5;focus.style.left=`${Math.max(4,rect.left-pad)}px`;focus.style.top=`${Math.max(4,rect.top-pad)}px`;focus.style.width=`${Math.max(12,rect.width+pad*2)}px`;focus.style.height=`${Math.max(12,rect.height+pad*2)}px`;const tipRect=tip.getBoundingClientRect(),margin=12;let left=Math.min(Math.max(margin,rect.left),window.innerWidth-tipRect.width-margin),top=rect.bottom+14;if(top+tipRect.height>window.innerHeight-margin)top=rect.top-tipRect.height-14;if(top<margin)top=Math.max(margin,window.innerHeight-tipRect.height-margin);tip.style.left=`${left}px`;tip.style.top=`${top}px`}
  function showStep(){buildLayer();const step=currentStep();layer.hidden=false;tip.querySelector('.guided-tour-count').textContent=`RECORRIDO · ${String(index+1).padStart(2,'0')} / ${steps.length}`;tip.querySelector('#guidedTourTitle').textContent=step.title;tip.querySelector('#guidedTourCopy').textContent=step.copy;tip.querySelector('.guided-tour-do').textContent=step.do?`Acción: ${step.do}`:'';tip.querySelector('.guided-tour-back').disabled=index===0;tip.querySelector('.guided-tour-next').textContent=index===steps.length-1?'Finalizar':'Siguiente';let attempts=0;const findAndPosition=()=>{if(!active())return;const target=document.querySelector(step.target);if(!target&&attempts++<12){setTimeout(findAndPosition,120);return}if(target){target.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});if(target.matches('button,a,select,input,[tabindex]'))setTimeout(()=>target.focus({preventScroll:true}),280);setTimeout(position,260);setTimeout(position,520)}else{tip.querySelector('.guided-tour-copy').textContent=`No encontré el control esperado. Puedes continuar o salir del recorrido. ${step.copy}`;focus.style.width='0';focus.style.height='0';position()}};findAndPosition();window.addEventListener('scroll',schedulePosition,{passive:true});window.addEventListener('resize',schedulePosition)}
  function actionTarget(event,step){const node=event.target instanceof Element?event.target:null;return node?.closest(step.target)||null}
  function completeAction(event,kind){if(!active())return;const step=currentStep();if(!step||step.action!==kind)return;const target=actionTarget(event,step);if(!target)return;if(step.action==='stop'&&!target.textContent.includes('Detener'))return;const next=index+1;index=next;storage.set(INDEX,index);if(index>=steps.length){finish();return}const nextStep=currentStep();if(target.closest('a')&&nextStep.page!==currentPage()){if(nextStep.page==='progresiones.html'&&storage.get(CLEAN)!=='1'){const destination=new URL(target.href,location.href);destination.searchParams.set('tour','1');target.href=destination.href;storage.set(CLEAN,'1')}return}if(nextStep.page!==currentPage()){routeTo(nextStep.page);return}setTimeout(showStep,140)}
  function start(){storage.set(ACTIVE,'1');storage.remove(CLEAN);index=0;storage.set(INDEX,index);routeTo('index.html')}
  function init(){const launch=document.getElementById('startGuidedTour');launch?.addEventListener('click',start);if(storage.get(DONE)==='1'&&currentPage()==='tutorial.html')showCompletionNotice();if(!active())return;index=Math.max(0,Math.min(steps.length,Number(storage.get(INDEX))||0));if(index>=steps.length){finish();return}if(currentPage()!==currentStep().page){routeTo(currentStep().page);return}showStep();document.addEventListener('click',event=>completeAction(event,'click'),true);document.addEventListener('change',event=>completeAction(event,'change'),true);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&active())stop()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
