const STORAGE={current:'circulo-studio-current-v1',ideas:'circulo-studio-ideas-v1'};
const KEY_ORDER=['C','G','D','A','E','B','F♯','D♭','A♭','E♭','B♭','F'];
const MINORS=['A','E','B','F♯','C♯','G♯','D♯','B♭','F','C','G','D'];
const SCALES={C:['C','D','E','F','G','A','B'],G:['G','A','B','C','D','E','F♯'],D:['D','E','F♯','G','A','B','C♯'],A:['A','B','C♯','D','E','F♯','G♯'],E:['E','F♯','G♯','A','B','C♯','D♯'],B:['B','C♯','D♯','E','F♯','G♯','A♯'],'F♯':['F♯','G♯','A♯','B','C♯','D♯','E♯'],'D♭':['D♭','E♭','F','G♭','A♭','B♭','C'],'A♭':['A♭','B♭','C','D♭','E♭','F','G'],'E♭':['E♭','F','G','A♭','B♭','C','D'],'B♭':['B♭','C','D','E♭','F','G','A'],'F':['F','G','A','B♭','C','D','E']};
const ROMANS={major:{triad:['I','ii','iii','IV','V','vi','vii°'],seventh:['Imaj7','ii7','iii7','IVmaj7','V7','vi7','viiø7']},minor:{triad:['i','ii°','III','iv','v','VI','VII'],seventh:['i7','iiø7','IIImaj7','iv7','v7','VImaj7','VII7']}};
const SUFFIX={major:{triad:['','m','m','','','m','°'],seventh:['maj7','m7','m7','maj7','7','m7','m7♭5']},minor:{triad:['m','°','','m','m','',''],seventh:['m7','m7♭5','maj7','m7','m7','maj7','7']}};
const DEGREE_NAMES={kick:'Bombo',clap:'Caja / clap',hat:'Hi-hat',bass:'Bajo'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function tonic(project){const index=KEY_ORDER.indexOf(project?.key);if(project?.mode==='minor'&&index>=0)return `${MINORS[index]} menor natural`;return `${project?.key||'C'} mayor`}
function projectScale(project){const scale=SCALES[project?.key]||SCALES.C;if(project?.mode!=='minor')return scale;return [...scale.slice(5),...scale.slice(0,5)]}
function describeChords(project){const mode=project.mode==='minor'?'minor':'major',notes=projectScale(project);return(Array.isArray(project.progression)?project.progression:[]).map(chord=>{const degree=Math.min(6,Math.max(0,Number(chord.degree)||0)),dominant=mode==='minor'&&degree===4&&String(chord.kind).startsWith('dominant'),seventh=chord.kind==='seventh'||chord.kind==='dominant7';if(dominant){let root=notes[4],roman=seventh?'V7':'V';return{name:`${root}${seventh?'7':''}`,roman,beats:Number(chord.beats)||4}}return{name:`${notes[degree]}${SUFFIX[mode][seventh?'seventh':'triad'][degree]}`,roman:ROMANS[mode][seventh?'seventh':'triad'][degree],beats:Number(chord.beats)||4}})}
function reportMarkup(project){const chords=describeChords(project),total=chords.reduce((sum,chord)=>sum+chord.beats,0),bars=total?Math.ceil(total/4):0,groove=project.groove||{},active=['kick','clap','hat'].filter(row=>Array.isArray(groove[row])&&groove[row].some(Boolean)),kit={house:'House · cálido',techno:'Techno · contundente',dembow:'Dembow · seco y subgrave'}[project.soundKit]||'House · cálido';const rhythm=active.length?(project.drumsEnabled?active.map(row=>DEGREE_NAMES[row]).join(' · '):'Batería silenciada'):'Sin batería';const bass=project.bassSteps?'Bajo por pasos':'Bajo sostenido con los acordes';return `<div class="idea-chords">${chords.length?chords.map(chord=>`<div class="idea-chord"><strong>${esc(chord.name)}</strong><span>${esc(chord.roman)} · ${chord.beats}p</span></div>`).join(''):'<span class="caption">Sin acordes guardados</span>'}</div><div class="idea-report"><div class="report-item"><span>SECUENCIA</span><strong>${esc(chords.map(chord=>chord.roman).join(' – ')||'Aún vacía')}</strong></div><div class="report-item"><span>TIEMPO</span><strong>${esc(`${Number(project.bpm)||100} BPM · ${total} pulsos · ${bars} ${bars===1?'compás':'compases'} aprox.`)}</strong></div><div class="report-item"><span>RITMO</span><strong>${esc(`${rhythm} · ${bass}`)}</strong></div><div class="report-item"><span>SONIDO DE REFERENCIA</span><strong>${esc(kit)} · disposición ${project.voicing==='root'?'fundamental':'cercana'}</strong></div></div>`}
function projectLink(idea){const params=new URLSearchParams({loadIdea:idea.id,key:idea.key||'C',mode:idea.mode==='minor'?'minor':'major'});return `./progresiones.html?${params.toString()}`}
function dateLabel(idea){const date=idea.createdAt?new Date(idea.createdAt):null;return date&&!Number.isNaN(date.getTime())?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(date):'Versión guardada'}
function render(){const list=read(STORAGE.ideas,[]),ideas=Array.isArray(list)?list:[],current=read(STORAGE.current,null),cards=$('ideaLibrary');$('ideaCount').textContent=`${ideas.length} ${ideas.length===1?'idea':'ideas'}`;const sessionSummary=$('sessionSummary');if(current?.progression?.length){const chords=describeChords(current);sessionSummary.textContent=`Sesión disponible: ${tonic(current)} · ${chords.map(chord=>chord.name).join(' – ')} · ${Number(current.bpm)||100} BPM. Guardarla crea una copia independiente de la sesión automática.`;$('saveSession').disabled=false}else{sessionSummary.textContent='Todavía no hay una progresión en la sesión. Ve a Crear, añade acordes y vuelve para guardar una versión.';$('saveSession').disabled=true}if(!ideas.length){cards.innerHTML='<div class="library-empty"><strong>Aún no tienes ideas guardadas.</strong><p>Arma una progresión en Crear y guárdala aquí con un nombre para tenerla como versión independiente.</p><a class="button primary" href="./progresiones.html">Ir a Crear ↗</a></div>';return}cards.innerHTML=ideas.map(idea=>`<article class="idea-card"><div class="idea-card-head"><div><h3>${esc(idea.name||'Idea sin nombre')}</h3><p class="idea-tonic">${esc(tonic(idea))} · ${Number(idea.progression?.length)||0} ${Number(idea.progression?.length)===1?'acorde':'acordes'}</p></div><time class="idea-date">${esc(dateLabel(idea))}</time></div>${reportMarkup(idea)}<div class="idea-actions"><a class="button primary" href="${esc(projectLink(idea))}">Retomar esta idea ↗</a><button class="button delete-idea" type="button" data-delete-idea="${esc(idea.id)}">Eliminar</button></div></article>`).join('')}
function saveCurrent(event){event.preventDefault();const current=read(STORAGE.current,null),status=$('captureStatus');if(!current?.progression?.length){status.textContent='Crea al menos un acorde en Crear antes de guardar una idea.';return}const ideas=read(STORAGE.ideas,[]);if(!Array.isArray(ideas)){status.textContent='No se pudieron leer las ideas guardadas en este navegador.';return}const name=$('sessionName').value.trim()||`Idea ${ideas.length+1}`,idea={...current,id:`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,createdAt:new Date().toISOString()};ideas.unshift(idea);if(!write(STORAGE.ideas,ideas)){status.textContent='No se pudo guardar. Comprueba el espacio disponible del navegador.';return}$('sessionName').value='';status.textContent=`«${name}» se guardó como una copia independiente.`;render()}
function deleteIdea(event){const button=event.target.closest('[data-delete-idea]');if(!button)return;const id=button.dataset.deleteIdea,ideas=read(STORAGE.ideas,[]);if(!Array.isArray(ideas))return;const selected=ideas.find(idea=>idea.id===id);if(!selected||!window.confirm(`¿Eliminar «${selected.name||'Idea sin nombre'}» de la biblioteca?`))return;if(write(STORAGE.ideas,ideas.filter(idea=>idea.id!==id))){$('captureStatus').textContent=`«${selected.name||'Idea'}» se eliminó de la biblioteca.`;render()}else{$('captureStatus').textContent='No se pudo actualizar la biblioteca.'}}
document.addEventListener('DOMContentLoaded',()=>{$('saveSessionForm').addEventListener('submit',saveCurrent);$('ideaLibrary').addEventListener('click',deleteIdea);render()});
