const PRACTICE_KEYS=['C','G','D','A','E','B','F♯','D♭','A♭','E♭','B♭','F'];
const PRACTICE_MINORS=['A','E','B','F♯','C♯','G♯','D♯','B♭','F','C','G','D'];
const PRACTICE_SCALES={C:['C','D','E','F','G','A','B'],G:['G','A','B','C','D','E','F♯'],D:['D','E','F♯','G','A','B','C♯'],A:['A','B','C♯','D','E','F♯','G♯'],E:['E','F♯','G♯','A','B','C♯','D♯'],B:['B','C♯','D♯','E','F♯','G♯','A♯'],'F♯':['F♯','G♯','A♯','B','C♯','D♯','E♯'],'D♭':['D♭','E♭','F','G♭','A♭','B♭','C'],'A♭':['A♭','B♭','C','D♭','E♭','F','G'],'E♭':['E♭','F','G','A♭','B♭','C','D'],'B♭':['B♭','C','D','E♭','F','G','A'],'F':['F','G','A','B♭','C','D','E']};
const PRACTICE_ROMAN={major:['I','ii','iii','IV','V','vi','vii°'],minor:['i','ii°','III','iv','v','VI','VII']};
const PRACTICE_SUFFIX={major:['','m','m','','','m','°'],minor:['m','°','','m','m','','']};
const PRACTICE_EXERCISES={cadence:{title:'Tensión y resolución',objective:'Haz que la tensión vuelva al centro tonal.',hint:'Pista: el acorde que está una quinta por encima suele empujar hacia la tónica.',degrees:[4,0],level:'RETO 01'},'major-pop':{title:'Progresión pop en mayor',objective:'Construye una frase de cuatro acordes que salga del reposo, cree tensión y vuelva a moverse.',hint:'Pista: prueba una combinación frecuente de I, V, vi y IV.',degrees:[0,4,5,3],level:'RETO 02'},'minor-loop':{title:'Loop en menor',objective:'Crea un recorrido donde el acorde menor sea el centro, pero otros grados aporten movimiento.',hint:'Pista: este loop usa i, VI, III y VII; observa que la tónica no tiene que ir siempre seguida de V.',degrees:[0,5,2,6],level:'RETO 03'}};
const practice$=id=>document.getElementById(id);
const practiceState={answers:[],hasChecked:false,showAnswer:false};
function practiceScale(){const scale=PRACTICE_SCALES[practice$('practiceKey').value]||PRACTICE_SCALES.C;return practice$('practiceMode').value==='minor'?[...scale.slice(5),...scale.slice(0,5)]:scale}
function exercise(){return PRACTICE_EXERCISES[practice$('practiceType').value]||PRACTICE_EXERCISES.cadence}
function currentTonic(){const keyIndex=PRACTICE_KEYS.indexOf(practice$('practiceKey').value);return practice$('practiceMode').value==='minor'?PRACTICE_MINORS[keyIndex]+'m':practice$('practiceKey').value}
function practiceRaisedSeventh(){const note=practiceScale()[6];if(note.includes('♭'))return note.replace('♭','');if(note.includes('♯'))return note.replace('♯','𝄪');return note+'♯'}
function practiceChord(degree){const mode=practice$('practiceMode').value,root=practiceScale()[degree],suffix=PRACTICE_SUFFIX[mode][degree];if(degree===4&&practice$('practiceType').value==='cadence')return{degree,name:`${root}7`,roman:'V7',kind:mode==='minor'?'dominant7':'seventh'};return{degree,name:`${root}${suffix}`,roman:PRACTICE_ROMAN[mode][degree],kind:'triad'}}
function selectedAnswers(){return[...practice$('practiceSlots').querySelectorAll('select')].map(select=>select.value===''?null:Number(select.value))}
function showInitialFeedback(){practiceState.hasChecked=false;practiceState.showAnswer=false;practice$('practiceFeedback').className='practice-feedback';practice$('practiceFeedback').textContent='Completa los acordes del reto y comprueba tu respuesta.';practice$('practiceExplanation').hidden=true;practice$('explainPractice').hidden=true;practice$('hearPractice').hidden=true}
function renderPractice(){const type=practice$('practiceType').value,config=exercise(),expected=config.degrees;practice$('practiceLevel').textContent=config.level;practice$('practiceObjective').textContent=config.objective;practice$('practiceHint').textContent=config.hint;practice$('practiceMode').disabled=type!=='cadence';if(type==='major-pop')practice$('practiceMode').value='major';if(type==='minor-loop')practice$('practiceMode').value='minor';const mode=practice$('practiceMode').value,keySelect=practice$('practiceKey'),selectedKey=keySelect.value||'C';keySelect.innerHTML=PRACTICE_KEYS.map((key,index)=>`<option value="${key}">${mode==='minor'?`${PRACTICE_MINORS[index]}m (relativa de ${key})`:`${key} mayor`}</option>`).join('');keySelect.value=selectedKey;const count=expected.length;if(practiceState.answers.length!==count)practiceState.answers=Array(count).fill('');practice$('practiceSlots').innerHTML=Array.from({length:count},(_,slot)=>`<label class="practice-slot"><span>ACORDE ${String(slot+1).padStart(2,'0')}</span><select aria-label="Elegir acorde ${slot+1}"><option value="">Elige un grado…</option>${PRACTICE_ROMAN[mode].map((roman,degree)=>{const chord=practiceChord(degree);return `<option value="${degree}" ${practiceState.answers[slot]===String(degree)?'selected':''}>${chord.name} · ${chord.roman}</option>`}).join('')}</select></label>`).join('');practice$('practiceSlots').querySelectorAll('select').forEach((select,index)=>select.addEventListener('change',()=>{practiceState.answers[index]=select.value;showInitialFeedback()}));showInitialFeedback()}
function explain(correct){const config=exercise(),mode=practice$('practiceMode').value,tonic=currentTonic(),chords=config.degrees.map(degree=>practiceChord(degree)),degreeNames=chords.map(chord=>chord.roman).join(' – '),names=chords.map(chord=>chord.name).join(' – ');let explanation;if(practice$('practiceType').value==='cadence')explanation=mode==='minor'?`<strong>${chords[0].roman} (${chords[0].name})</strong> contiene la sensible elevada y crea una atracción fuerte hacia <strong>${chords[1].roman} (${chords[1].name})</strong>, el centro de ${tonic}. Escucha cómo ${practiceRaisedSeventh()} tiende a subir a ${practiceScale()[0]}.`:`<strong>${chords[0].roman} (${chords[0].name})</strong> concentra la tensión —su séptima, si se usa, añade otra nota inestable— y <strong>${chords[1].roman} (${chords[1].name})</strong> la resuelve en la tónica.`;else if(mode==='major')explanation=`<strong>I</strong> establece el hogar; <strong>V</strong> aporta tensión, <strong>vi</strong> ofrece un color relativo menor y <strong>IV</strong> prepara el regreso. Escucha qué cambia si alteras el orden.`;else explanation=`<strong>i</strong> establece el centro menor; <strong>VI</strong> y <strong>III</strong> comparten notas y dan contraste; <strong>VII</strong> abre un camino de vuelta. Aquí usamos menor natural, no una cadencia dominante.`;practice$('practiceExplanation').innerHTML=`<strong>Solución objetivo: ${degreeNames} · ${names}.</strong> ${explanation}<br>Este reto comprueba una ruta útil, no la única progresión musicalmente válida.`;practice$('practiceExplanation').hidden=false;practice$('explainPractice').hidden=true;const kinds=chords.map(chord=>chord.kind);if(practice$('practiceType').value==='cadence'&&mode==='major')kinds[0]='seventh';const params=new URLSearchParams({key:practice$('practiceKey').value,mode,degrees:config.degrees.join(','),kinds:kinds.join(',')});practice$('hearPractice').href=`./progresiones.html?${params.toString()}`;practice$('hearPractice').hidden=!correct}
function checkPractice(){const selected=selectedAnswers(),config=exercise();if(selected.some(value=>value===null)){practice$('practiceFeedback').className='practice-feedback retry';practice$('practiceFeedback').textContent='Elige un acorde para cada posición y vuelve a comprobar.';return}const correct=selected.length===config.degrees.length&&selected.every((degree,index)=>degree===config.degrees[index]);practice$('practiceFeedback').className=`practice-feedback ${correct?'success':'retry'}`;practice$('practiceFeedback').textContent=correct?'¡Bien! Has encontrado la solución objetivo. Ahora escúchala y prueba una variación.':'Todavía no coincide con la ruta objetivo. Revisa qué función cumple cada acorde o abre la solución comentada.';if(correct)explain(true);else{practice$('practiceExplanation').hidden=true;practice$('explainPractice').hidden=false;practice$('hearPractice').hidden=true}}
function initPractice(){const params=new URLSearchParams(location.search),key=PRACTICE_KEYS.includes(params.get('key'))?params.get('key'):'C',mode=params.get('mode')==='minor'?'minor':'major';practice$('practiceKey').innerHTML=PRACTICE_KEYS.map(keyName=>`<option value="${keyName}">${keyName}</option>`).join('');practice$('practiceKey').value=key;practice$('practiceMode').value=mode;practice$('practiceType').addEventListener('change',()=>{practiceState.answers=[];renderPractice()});practice$('practiceKey').addEventListener('change',renderPractice);practice$('practiceMode').addEventListener('change',renderPractice);practice$('checkPractice').addEventListener('click',checkPractice);practice$('explainPractice').addEventListener('click',()=>{explain(false);practice$('practiceExplanation').hidden=false;practice$('explainPractice').hidden=true});renderPractice()}
if(document.getElementById('practiceSlots'))initPractice();
