const KEYS=['C','G','D','A','E','B','F♯','D♭','A♭','E♭','B♭','F'];
const MINORS=['A','E','B','F♯','C♯','G♯','D♯','B♭','F','C','G','D'];
const SCALES={C:['C','D','E','F','G','A','B'],G:['G','A','B','C','D','E','F♯'],D:['D','E','F♯','G','A','B','C♯'],A:['A','B','C♯','D','E','F♯','G♯'],E:['E','F♯','G♯','A','B','C♯','D♯'],B:['B','C♯','D♯','E','F♯','G♯','A♯'],'F♯':['F♯','G♯','A♯','B','C♯','D♯','E♯'],'D♭':['D♭','E♭','F','G♭','A♭','B♭','C'],'A♭':['A♭','B♭','C','D♭','E♭','F','G'],'E♭':['E♭','F','G','A♭','B♭','C','D'],'B♭':['B♭','C','D','E♭','F','G','A'],'F':['F','G','A','B♭','C','D','E']};
const SIGNATURES=['Sin alteraciones','1 sostenido','2 sostenidos','3 sostenidos','4 sostenidos','5 sostenidos','6 sostenidos','5 bemoles','4 bemoles','3 bemoles','2 bemoles','1 bemol'];
const CHORDS={major:{triad:{roman:['I','ii','iii','IV','V','vi','vii°'],suffix:['','m','m','','','m','°'],quality:['maj','min','min','maj','maj','min','dim']},seventh:{roman:['Imaj7','ii7','iii7','IVmaj7','V7','vi7','viiø7'],suffix:['maj7','m7','m7','maj7','7','m7','m7♭5'],quality:['maj7','min7','min7','maj7','dom7','min7','halfdim7']}},minor:{triad:{roman:['i','ii°','III','iv','v','VI','VII'],suffix:['m','°','','m','m','',''],quality:['min','dim','maj','min','min','maj','maj']},seventh:{roman:['i7','iiø7','IIImaj7','iv7','v7','VImaj7','VII7'],suffix:['m7','m7♭5','maj7','m7','m7','maj7','7'],quality:['min7','halfdim7','maj7','min7','min7','maj7','dom7']}}};
const INTERVALS={maj:[0,4,7],min:[0,3,7],dim:[0,3,6],maj7:[0,4,7,11],min7:[0,3,7,10],dom7:[0,4,7,10],halfdim7:[0,3,6,10]};
const ROLES=['Reposo','Preparación','Color','Preparación','Tensión','Color','Tensión'];
const GROOVE_ROWS=['kick','clap','hat','bass'];
const GROOVE_LABELS={kick:'Bombo',clap:'Caja / clap',hat:'Hi-hat',bass:'Bajo'};
const GROOVE_PRESETS={
  house:{kick:[0,4,8,12],clap:[4,12],hat:[2,6,10,14],bass:[2,6,10,14]},
  techno:{kick:[0,4,8,12],clap:[4,12],hat:[2,3,6,7,10,11,14,15],bass:[0,7,10,15]},
  dembow:{kick:[0,4,8,11],clap:[3,6,11,14],hat:[0,2,4,6,8,10,12,14],bass:[0,4,8,11]},
  empty:{kick:[],clap:[],hat:[],bass:[]}
};
const SOUND_KITS={
  house:{name:'House',kick:{wave:'sine',start:145,end:52,decay:.24,level:.30},clap:{filter:'highpass',cutoff:1500,decay:.15,level:.16},hat:{cutoff:7000,decay:.07,level:.065},bass:{wave:'triangle',cutoff:650,decay:.19,level:.13}},
  techno:{name:'Techno',kick:{wave:'triangle',start:195,end:43,decay:.34,level:.33},clap:{filter:'highpass',cutoff:1900,decay:.21,level:.18},hat:{cutoff:5500,decay:.12,level:.085},bass:{wave:'sawtooth',cutoff:420,decay:.23,level:.085}},
  dembow:{name:'Dembow',kick:{wave:'sine',start:120,end:47,decay:.18,level:.34},clap:{filter:'bandpass',cutoff:2500,decay:.095,level:.19},hat:{cutoff:8200,decay:.045,level:.055},bass:{wave:'sine',cutoff:900,decay:.34,level:.16}}
};
function kitName(value){return SOUND_KITS[value]?value:'house'}
function emptyGroove(){return Object.fromEntries(GROOVE_ROWS.map(row=>[row,Array(16).fill(0)]))}
function cleanGroove(value){const result=emptyGroove();GROOVE_ROWS.forEach(row=>{if(Array.isArray(value?.[row]))result[row]=result[row].map((_,i)=>row==='bass'?([0,1,2,3].includes(value[row][i])?value[row][i]:0):(value[row][i]===1?1:0))});return result}
function presetGroove(name){const result=emptyGroove(),preset=GROOVE_PRESETS[name];if(preset)GROOVE_ROWS.forEach(row=>preset[row].forEach(step=>{result[row][step]=1}));return result}
const STYLE_RECIPES={
  house:{mode:'major',bpm:124,extension:'triad',chords:[[0,'triad',4],[4,'triad',4],[5,'triad',4],[3,'triad',4]],info:'Cuatro compases I–V–vi–IV con bombo a negras y bajo a contratiempos. Edita los 16 pasos y exporta las pistas.'},
  'deep-house':{mode:'minor',bpm:124,extension:'seventh',chords:[[0,'seventh',4],[5,'seventh',4],[2,'seventh',4],[6,'seventh',4]],info:'Séptimas y voces cercanas con base house editable. Trabaja el swing, timbre y mezcla en tu DAW.'},
  'tech-house':{mode:'minor',bpm:128,extension:'triad',chords:[[0,'triad',8]],info:'Un centro tonal durante dos compases y bajo sincopado. Útiles: loop, pasos de bajo y exportación MIDI.'},
  'minimal-techno':{mode:'minor',bpm:130,extension:'triad',chords:[[0,'triad',8]],info:'Un pedal de dos compases con patrón editable. Cambia densidad, motivos y timbre después en tu DAW.'},
  'melodic-techno':{mode:'minor',bpm:128,extension:'triad',chords:[[0,'triad',4],[5,'triad',4],[2,'triad',4],[6,'triad',4]],info:'Cuatro compases i–VI–III–VII. Usa voces cercanas, pasos de bajo y MIDI separado para arpegios y capas.'},
  'reggaeton-classic':{mode:'minor',bpm:94,extension:'triad',chords:[[0,'triad',4],[6,'triad',4],[5,'triad',4],[4,'dominant',4]],info:'Descenso i–VII–VI–V con boceto de dembow editable. Ajusta percusión, bajo y acentos a tu tema.'},
  'reggaeton-modern':{mode:'minor',bpm:92,extension:'seventh',chords:[[0,'seventh',8],[5,'seventh',8]],info:'Dos acordes amplios con boceto de dembow. Deja espacio a la voz; diseña el 808 y sus slides en tu DAW.'}
};
const PROJECT_KEY='circulo-studio-current-v1',IDEAS_KEY='circulo-studio-ideas-v1',BACKUP_KEY='circulo-studio-backup-v1';
const $=id=>document.getElementById(id);
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
const url=new URLSearchParams(location.search);
let ideas=readStore(IDEAS_KEY,[]);if(!Array.isArray(ideas))ideas=[];
const requestedIdea=ideas.find(idea=>idea.id===url.get('loadIdea'));
const currentProject=readStore(PROJECT_KEY,{});
const degreeTokens=url.get('degrees')?.split(',')||[];
const kindTokens=url.get('kinds')?.split(',')||[];
const customProgression=degreeTokens.length>0&&degreeTokens.length<=8&&degreeTokens.every(value=>/^\d$/.test(value)&&Number(value)<=6)?degreeTokens.map((value,index)=>({degree:Number(value),kind:['triad','seventh','dominant','dominant7'].includes(kindTokens[index])?kindTokens[index]:'triad',beats:4})):null;
const requestedPractice=customProgression?{...currentProject,key:KEYS.includes(url.get('key'))?url.get('key'):currentProject.key||'C',mode:url.get('mode')==='minor'?'minor':'major',progression:customProgression}:null;
const requestedTour=url.get('tour')==='1'?{...currentProject,key:KEYS.includes(url.get('key'))?url.get('key'):currentProject.key||'C',mode:url.get('mode')==='minor'?'minor':'major',progression:[]}:null;
const requestedProject=requestedIdea||requestedPractice||requestedTour;
if(requestedProject&&currentProject.progression?.length)writeStore(BACKUP_KEY,currentProject);
const saved=requestedProject||currentProject;
const state={key:KEYS.includes(url.get('key'))?url.get('key'):KEYS.includes(saved.key)?saved.key:'C',mode:url.get('mode')==='major'||url.get('mode')==='minor'?url.get('mode'):saved.mode==='minor'?'minor':'major',bpm:Math.min(240,Math.max(40,Number(saved.bpm)||100)),voicing:saved.voicing==='root'?'root':'smooth',loop:Boolean(saved.loop),alignBars:saved.alignBars!==false,extension:saved.extension==='seventh'?'seventh':'triad',defaultBeats:[1,2,4,8].includes(saved.defaultBeats)?saved.defaultBeats:4,progression:Array.isArray(saved.progression)?saved.progression.filter(c=>Number.isInteger(c.degree)&&c.degree>=0&&c.degree<=6).slice(0,8).map(c=>({degree:c.degree,kind:['triad','seventh','dominant','dominant7'].includes(c.kind)?c.kind:'triad',beats:[1,2,4,8].includes(c.beats)?c.beats:4})):[],groove:cleanGroove(saved.groove),drumsEnabled:Boolean(saved.drumsEnabled),bassSteps:Boolean(saved.bassSteps),soundKit:kitName(saved.soundKit),selected:null,playingIndex:null};
let undoStack=[],audioContext=null,activeMasters=[],timers=[],isPlaying=false,playToken=0;
function root(){return state.mode==='major'?state.key:MINORS[KEYS.indexOf(state.key)]}
function fullName(){return root()+(state.mode==='major'?' mayor':' menor natural')}
function scale(){const notes=SCALES[state.key];return state.mode==='major'?notes:[...notes.slice(5),...notes.slice(0,5)]}
function parallelKey(mode){const names=mode==='major'?KEYS:MINORS,tonic=root(),exact=names.indexOf(tonic);const index=exact>=0?exact:names.findIndex(note=>notePc(note)===notePc(tonic));return KEYS[index]}
function totalBeats(){return state.progression.reduce((sum,chord)=>sum+chord.beats,0)}
function paddingBeats(){const remainder=totalBeats()%4;return state.alignBars&&remainder?4-remainder:0}
function raiseNote(note){if(note.includes('♭'))return note.replace('♭','');if(note.includes('♯'))return note.replace('♯','𝄪');return note+'♯'}
function describe(def){const degree=def.degree,kind=def.kind,notes=scale(),dominant=state.mode==='minor'&&degree===4&&kind.startsWith('dominant'),seventh=kind==='seventh'||kind==='dominant7';if(dominant){const rootNote=notes[4],tones=[rootNote,raiseNote(notes[6]),notes[1]];if(seventh)tones.push(notes[3]);return{...def,root:rootNote,name:rootNote+(seventh?'7':''),roman:seventh?'V7':'V',quality:seventh?'dom7':'maj',tones,role:'Tensión'}}const form=CHORDS[state.mode][seventh?'seventh':'triad'];return{...def,root:notes[degree],name:notes[degree]+form.suffix[degree],roman:form.roman[degree],quality:form.quality[degree],tones:Array.from({length:seventh?4:3},(_,i)=>notes[(degree+i*2)%7]),role:ROLES[degree]}}
function project(){return{key:state.key,mode:state.mode,bpm:state.bpm,voicing:state.voicing,loop:state.loop,alignBars:state.alignBars,extension:state.extension,defaultBeats:state.defaultBeats,progression:state.progression.map(c=>({...c})),groove:cleanGroove(state.groove),drumsEnabled:state.drumsEnabled,bassSteps:state.bassSteps,soundKit:state.soundKit}}
function restoreProject(source){state.key=KEYS.includes(source.key)?source.key:'C';state.mode=source.mode==='minor'?'minor':'major';state.bpm=Math.min(240,Math.max(40,Math.round(Number(source.bpm)||100)));state.voicing=source.voicing==='root'?'root':'smooth';state.loop=Boolean(source.loop);state.alignBars=source.alignBars!==false;state.extension=source.extension==='seventh'?'seventh':'triad';state.defaultBeats=[1,2,4,8].includes(source.defaultBeats)?source.defaultBeats:4;state.progression=Array.isArray(source.progression)?source.progression.filter(c=>Number.isInteger(c.degree)&&c.degree>=0&&c.degree<=6).slice(0,8).map(c=>({degree:c.degree,kind:['triad','seventh','dominant','dominant7'].includes(c.kind)?c.kind:'triad',beats:[1,2,4,8].includes(c.beats)?c.beats:4})):[];state.groove=cleanGroove(source.groove);state.drumsEnabled=Boolean(source.drumsEnabled);state.bassSteps=Boolean(source.bassSteps);state.soundKit=kitName(source.soundKit);state.selected=null;state.playingIndex=null}
function backupDraft(){const current=project();if(current.progression.length)writeStore(BACKUP_KEY,current);renderRecovery()}
function renderRecovery(){const backup=readStore(BACKUP_KEY,null);$('recoverDraft').disabled=!backup||JSON.stringify(backup)===JSON.stringify(project())}
function renderStyleInfo(){const recipe=STYLE_RECIPES[$('styleSelect').value];$('applyStyle').disabled=!recipe;$('styleInfo').textContent=recipe?recipe.info:'Un boceto armónico y rítmico editable. Los sonidos son una maqueta, no una producción terminada.'}
function applyStyle(){const name=$('styleSelect').value,recipe=STYLE_RECIPES[name];if(!recipe)return;stopPlayback();checkpoint();backupDraft();if(state.mode!==recipe.mode){state.key=parallelKey(recipe.mode);state.mode=recipe.mode}state.bpm=recipe.bpm;state.extension=recipe.extension;state.alignBars=true;state.progression=recipe.chords.map(([degree,kind,beats])=>({degree,kind,beats}));state.soundKit=name.startsWith('reggaeton')?'dembow':name.includes('techno')?'techno':'house';state.groove=presetGroove(state.soundKit);state.drumsEnabled=true;state.bassSteps=true;state.selected=null;persist();render();setStatus('Boceto armónico, rítmico y sonoro cargado. El borrador anterior sigue recuperable.')}
function persist(){if(!writeStore(PROJECT_KEY,project()))setStatus('No se pudo guardar en este navegador. Exporta MIDI para conservar la idea.',true)}
function setStatus(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error)}
function syncUrl(){const address=new URL(location.href);address.searchParams.delete('loadIdea');address.searchParams.delete('degrees');address.searchParams.delete('kinds');address.searchParams.delete('tour');address.searchParams.set('key',state.key);address.searchParams.set('mode',state.mode);history.replaceState(null,'',address);document.querySelectorAll('[data-page-link]').forEach(link=>{const target=new URL(link.dataset.pageLink,location.href);target.searchParams.set('key',state.key);target.searchParams.set('mode',state.mode);link.href=target})}
function fillKeySelect(){const select=$('keySelect');select.innerHTML=KEYS.map((key,i)=>`<option value="${key}">${state.mode==='major'?key:MINORS[i]+'m'}</option>`).join('');select.value=state.key;$('modeSelect').value=state.mode}
function chordOptions(){const kind=state.extension;const options=Array.from({length:7},(_,degree)=>({degree,kind,beats:state.defaultBeats}));if(state.mode==='minor')options.push({degree:4,kind:kind==='seventh'?'dominant7':'dominant',beats:state.defaultBeats});return options}
function renderChords(){const options=chordOptions();$('extensionTriad').setAttribute('aria-pressed',state.extension==='triad');$('extensionSeventh').setAttribute('aria-pressed',state.extension==='seventh');$('minorHelp').hidden=state.mode!=='minor';$('composerChords').innerHTML=options.map((option,i)=>{const c=describe(option);return `<div class="studio-chord"><button type="button" class="chord-button" data-add="${i}" aria-label="Añadir ${c.name}, grado ${c.roman}"><span class="roman">${c.roman}</span><span><strong>${c.name}</strong><small>${c.tones.join(' · ')} <span class="chord-role">${c.role}</span></small></span><span class="plus" aria-hidden="true">+</span></button><button type="button" class="audition" data-audition="${i}" aria-label="Escuchar ${c.name}" title="Escuchar ${c.name}">♫</button></div>`}).join('')}
function renderProgression(){const total=totalBeats(),padding=paddingBeats(),length=total+padding,bars=Number((length/4).toFixed(2));$('totalBeats').textContent=`${total} ${total===1?'pulso':'pulsos'}`;$('totalTime').textContent=`${(length*60/state.bpm).toFixed(1)} s · ${bars===1?'1 compás':`${bars} compases`}`;const notice=$('barNotice');notice.classList.toggle('warning',Boolean(total%4&&!state.alignBars));notice.textContent=!total?'':padding?`Se añaden ${padding} ${padding===1?'pulso de silencio':'pulsos de silencio'} al final para cerrar el compás.`:total%4?'Loop libre: el inicio se desplazará respecto a una base de 4/4.':'El loop termina justo al final del compás.';$('progressGrid').innerHTML=Array.from({length:8},(_,i)=>{const def=state.progression[i],c=def?describe(def):null;return `<button type="button" class="measure ${c?'filled':''} ${state.selected===i?'selected':''} ${state.playingIndex===i?'playing':''}" data-slot="${i}" aria-label="${c?`Seleccionar ${c.name}, posición ${i+1}`:`Posición ${i+1} vacía`}" aria-pressed="${state.selected===i}"><span class="number">${String(i+1).padStart(2,'0')}</span>${c?`<strong>${c.name}</strong><span class="roman">${c.roman} · ${c.beats} ${c.beats===1?'pulso':'pulsos'}</span>`:'<span>—</span>'}</button>`}).join('');$('progressHelp').textContent=state.progression.length?`${state.progression.length} ${state.progression.length===1?'acorde':'acordes'}. Selecciona una posición para reemplazarla, moverla o cambiar su duración.`:'Elige un acorde de la lista para comenzar.';$('play').disabled=!state.progression.length;$('exportMidi').disabled=!state.progression.length;$('undo').disabled=!undoStack.length;$('clear').disabled=!state.progression.length;renderEditor();renderRecovery()}
function renderEditor(){const i=state.selected,valid=i!==null&&Boolean(state.progression[i]);$('selectionTitle').textContent=valid?`Posición ${i+1}: ${describe(state.progression[i]).name}`:'Próximo acorde';$('selectionHint').textContent=valid?'Elige otro acorde para reemplazarlo o ajusta su duración.':'Elige cuánto durará; pulsa una posición para editarla.';$('beats').value=String(valid?state.progression[i].beats:state.defaultBeats);$('moveLeft').disabled=!valid||i===0;$('moveRight').disabled=!valid||i===state.progression.length-1;$('removeChord').disabled=!valid}
function renderGroove(){
  $('drumsEnabled').checked=state.drumsEnabled;$('bassSteps').checked=state.bassSteps;$('soundKit').value=state.soundKit;
  $('grooveHint').textContent=state.bassSteps?'El bajo toma la raíz, quinta u octava del acorde que suena en cada paso.':'El bajo sostenido original continúa activo hasta elegir “Bajo por pasos”.';
  $('grooveGrid').innerHTML=`<div class="groove-corner">Pista</div>${Array.from({length:16},(_,i)=>`<span class="groove-step-label ${i%4===0?'beat':''}">${i%4===0?1+i/4:['','e','&','a'][i%4]}</span>`).join('')}`+GROOVE_ROWS.map(row=>`<span class="groove-row-label">${GROOVE_LABELS[row]} <button type="button" class="groove-preview" data-preview="${row}" aria-label="Probar sonido de ${GROOVE_LABELS[row]}" title="Probar ${GROOVE_LABELS[row]}">♫</button></span>${state.groove[row].map((value,i)=>`<button type="button" class="groove-cell ${value?'on':''} ${i%4===0?'beat':''}" data-row="${row}" data-step="${i}" data-value="${value}" aria-label="${GROOVE_LABELS[row]}, pulso ${1+Math.floor(i/4)} paso ${1+i%4}: ${row==='bass'?['silencio','raíz','quinta','octava'][value]:value?'activo':'inactivo'}" aria-pressed="${Boolean(value)}" title="${row==='bass'?['Silencio','Raíz','Quinta','Octava'][value]:value?'Activo':'Silencio'}">${row==='bass'?['·','R','5','8'][value]:value?'●':'·'}</button>`).join('')}`).join('');
  const drumsOption=$('midiPart').querySelector('[value="drums"]');if(drumsOption)drumsOption.disabled=!state.drumsEnabled;
  if(!state.drumsEnabled&&$('midiPart').value==='drums')$('midiPart').value='all';
  $('undo').disabled=!undoStack.length;renderRecovery();
}
function render(){fillKeySelect();syncUrl();$('composerKey').textContent=fullName();$('composerSignature').textContent=SIGNATURES[KEYS.indexOf(state.key)];$('relativeKey').textContent=`Ir a relativa ${state.mode==='major'?MINORS[KEYS.indexOf(state.key)]+'m':state.key}`;$('bpm').value=state.bpm;$('voicing').value=state.voicing;$('loop').checked=state.loop;$('alignBars').checked=state.alignBars;$('presetName').textContent=state.mode==='major'?'I – V – vi – IV':'i – VI – III – VII';renderChords();renderProgression();renderGroove();renderIdeas();renderRecovery();renderStyleInfo()}
function checkpoint(){undoStack.push(project());if(undoStack.length>30)undoStack.shift()}
function changeProgression(mutator){stopPlayback();checkpoint();mutator();persist();renderProgression()}
function changeKey(key,mode){if(key===state.key&&mode===state.mode)return;const modeChanged=mode!==state.mode;stopPlayback();checkpoint();state.key=key;state.mode=mode;state.selected=null;persist();render();setStatus(state.progression.length?(modeChanged?`Grados conservados en ${fullName()}; las notas se adaptaron.`:`Grados conservados; progresión transportada a ${fullName()}.`):`Tonalidad: ${fullName()}.`)}
function addChord(option){if(state.selected!==null&&state.progression[state.selected]){const i=state.selected;changeProgression(()=>{state.progression[i]={...option,beats:state.progression[i].beats};state.selected=null});setStatus(`Acorde reemplazado por ${describe(option).name}.`);return}if(state.progression.length>=8){setStatus('La secuencia admite hasta 8 acordes. Selecciona una posición para reemplazarla.',true);return}changeProgression(()=>{state.progression.push({...option,beats:state.defaultBeats})});setStatus(`${describe(option).name} añadido.`)}
function selectSlot(i){if(!state.progression[i])return;state.selected=state.selected===i?null:i;renderProgression()}
function moveSelected(direction){const i=state.selected,j=i+direction;if(i===null||j<0||j>=state.progression.length)return;changeProgression(()=>{[state.progression[i],state.progression[j]]=[state.progression[j],state.progression[i]];state.selected=j});setStatus('Acorde movido.')}
function removeSelected(){const i=state.selected;if(i===null)return;changeProgression(()=>{state.progression.splice(i,1);state.selected=null});setStatus('Acorde quitado.')}
function renderIdeas(){const select=$('savedIdeas'),selected=select.value;select.innerHTML='';if(!ideas.length)select.add(new Option('Ninguna idea guardada',''));else ideas.forEach(idea=>{const index=KEYS.indexOf(idea.key),keyName=idea.mode==='minor'&&index>=0?MINORS[index]+'m':idea.key;select.add(new Option(`${idea.name} · ${keyName}`,idea.id))});if(ideas.some(idea=>idea.id===selected))select.value=selected;$('loadIdea').disabled=!ideas.length;$('deleteIdea').disabled=!ideas.length}
function saveIdea(){if(!state.progression.length){$('saveStatus').textContent='Añade al menos un acorde antes de guardar una versión.';return}const name=$('ideaName').value.trim()||`Idea ${ideas.length+1}`;ideas.unshift({id:String(Date.now())+'-'+Math.random().toString(36).slice(2,7),name,createdAt:new Date().toISOString(),...project()});if(writeStore(IDEAS_KEY,ideas)){$('ideaName').value='';renderIdeas();$('savedIdeas').value=ideas[0].id;$('saveStatus').textContent=`«${name}» guardada en este navegador.`}else{$('saveStatus').textContent='No se pudo guardar la idea en este navegador.'}}
function loadIdea(){const idea=ideas.find(item=>item.id===$('savedIdeas').value);if(!idea)return;stopPlayback();checkpoint();backupDraft();restoreProject(idea);persist();render();$('savedIdeas').value=idea.id;$('saveStatus').textContent=`«${idea.name}» cargada. El borrador anterior se puede recuperar.`;setStatus('Idea cargada.')}
function recoverDraft(){const backup=readStore(BACKUP_KEY,null);if(!backup)return;stopPlayback();checkpoint();const previous=project();restoreProject(backup);writeStore(BACKUP_KEY,previous);persist();render();$('saveStatus').textContent='Borrador recuperado. Puedes pulsar de nuevo para volver al proyecto anterior.';setStatus('Borrador recuperado.')}
function deleteIdea(){const id=$('savedIdeas').value,idea=ideas.find(item=>item.id===id);if(!idea)return;ideas=ideas.filter(item=>item.id!==id);writeStore(IDEAS_KEY,ideas);renderIdeas();$('saveStatus').textContent=`«${idea.name}» eliminada de las versiones guardadas.`}
function notePc(note){const base={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[note[0]];const offset=(note.match(/♯/g)||[]).length+2*(note.match(/𝄪/g)||[]).length-(note.match(/♭/g)||[]).length;return(base+offset+12)%12}
function voiceChord(c,previous){const base=60+notePc(c.root),notes=INTERVALS[c.quality].map(i=>base+i);if(state.voicing==='root')return notes;let best=notes,bestScore=Infinity;for(let inv=0;inv<notes.length;inv++){const rotated=notes.map((n,i)=>i<inv?n+12:n).sort((a,b)=>a-b);for(const shift of [-12,0,12]){const candidate=rotated.map(n=>n+shift),center=candidate.reduce((a,b)=>a+b,0)/candidate.length,rangePenalty=candidate.reduce((sum,n)=>sum+(n<55?55-n:0)+(n>82?n-82:0),0)*12;const motion=previous?candidate.reduce((sum,n,i)=>sum+Math.abs(n-(previous[Math.min(i,previous.length-1)]??67)),0):Math.abs(center-67)*2;const score=motion+rangePenalty;if(score<bestScore){bestScore=score;best=candidate}}}return best}
function voiceSequence(){let previous=null;return state.progression.map(def=>{const c=describe(def),upper=voiceChord(c,previous),bass=48+notePc(c.root);previous=upper;return{...c,upper,bass}})}
function grooveEvents(chords=voiceSequence()){
  const events=[],ends=[];let end=0;chords.forEach(c=>{end+=c.beats;ends.push(end)});
  for(let step=0;step<end*4;step++){
    const beat=step/4,position=step%16;
    if(state.drumsEnabled)for(const row of ['kick','clap','hat'])if(state.groove[row][position])events.push({beat,row});
    if(state.bassSteps&&state.groove.bass[position]){const chordIndex=ends.findIndex(limit=>beat<limit),chord=chords[chordIndex],interval=[0,0,7,12][state.groove.bass[position]],remaining=ends[chordIndex]-beat;events.push({beat,row:'bass',note:chord.bass+interval,duration:Math.min(.23,remaining)})}
  }
  return events;
}
function midiHz(note){return 440*Math.pow(2,(note-69)/12)}
function scheduleNote(midi,time,duration,volume,type,destination){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type;osc.frequency.value=midiHz(midi);const end=time+Math.max(.12,duration*.9);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(volume,time+.025);gain.gain.setValueAtTime(volume*.72,Math.max(time+.03,end-.12));gain.gain.exponentialRampToValueAtTime(.001,end);osc.connect(gain).connect(destination);osc.start(time);osc.stop(end+.015)}
function scheduleChord(c,time,duration,destination,withBass=true){if(withBass)scheduleNote(c.bass,time,duration,.1,'sine',destination);c.upper.forEach(n=>scheduleNote(n,time,duration,.055,'triangle',destination))}
let noiseBuffer=null;
function scheduleDrum(row,time,destination){
  const profile=SOUND_KITS[state.soundKit][row];if(!profile)return;
  if(row==='kick'){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=profile.wave;osc.frequency.setValueAtTime(profile.start,time);osc.frequency.exponentialRampToValueAtTime(profile.end,time+profile.decay*.7);gain.gain.setValueAtTime(profile.level,time);gain.gain.exponentialRampToValueAtTime(.001,time+profile.decay);osc.connect(gain).connect(destination);osc.start(time);osc.stop(time+profile.decay+.01);return}
  if(!noiseBuffer){noiseBuffer=audioContext.createBuffer(1,Math.round(audioContext.sampleRate*.25),audioContext.sampleRate);const samples=noiseBuffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=Math.random()*2-1}
  const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=noiseBuffer;filter.type=profile.filter||'highpass';filter.frequency.value=profile.cutoff;gain.gain.setValueAtTime(profile.level,time);gain.gain.exponentialRampToValueAtTime(.001,time+profile.decay);source.connect(filter).connect(gain).connect(destination);source.start(time);source.stop(time+profile.decay+.01)
}
function scheduleBassStep(note,time,duration,destination){const profile=SOUND_KITS[state.soundKit].bass,osc=audioContext.createOscillator(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain(),length=Math.max(duration,profile.decay);osc.type=profile.wave;osc.frequency.value=midiHz(note);filter.type='lowpass';filter.frequency.setValueAtTime(Math.max(profile.cutoff*1.8,profile.cutoff+100),time);filter.frequency.exponentialRampToValueAtTime(profile.cutoff,time+Math.min(.12,length));gain.gain.setValueAtTime(.001,time);gain.gain.linearRampToValueAtTime(profile.level,time+.008);gain.gain.exponentialRampToValueAtTime(.001,time+length);osc.connect(filter).connect(gain).connect(destination);osc.start(time);osc.stop(time+length+.01)}
function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function stopPlayback(){playToken++;clearTimers();activeMasters.forEach(master=>{if(audioContext)master.gain.setTargetAtTime(0,audioContext.currentTime,.018)});activeMasters=[];isPlaying=false;state.playingIndex=null;$('play').textContent='▶ Escuchar';document.querySelectorAll('.measure.playing').forEach(el=>el.classList.remove('playing'))}
function playCycle(token,startAt){if(!isPlaying||token!==playToken)return;const chords=voiceSequence(),master=activeMasters[0],beatSeconds=60/state.bpm;let elapsed=0;timers=[];chords.forEach((c,i)=>{const duration=c.beats*beatSeconds,when=startAt+elapsed;scheduleChord(c,when,duration,master,!state.bassSteps);const index=i;timers.push(setTimeout(()=>{if(token!==playToken)return;state.playingIndex=index;document.querySelectorAll('.measure').forEach((el,j)=>el.classList.toggle('playing',j===index))},Math.max(0,(when-audioContext.currentTime)*1000)));elapsed+=duration});grooveEvents(chords).forEach(event=>{const when=startAt+event.beat*beatSeconds;if(event.row==='bass')scheduleBassStep(event.note,when,event.duration*beatSeconds,master);else scheduleDrum(event.row,when,master)});if(paddingBeats())timers.push(setTimeout(()=>{if(token!==playToken)return;state.playingIndex=null;document.querySelectorAll('.measure.playing').forEach(el=>el.classList.remove('playing'))},Math.max(0,(startAt+elapsed-audioContext.currentTime)*1000)));const endAt=startAt+elapsed+paddingBeats()*beatSeconds;timers.push(setTimeout(()=>{if(token!==playToken)return;if(state.loop)playCycle(token,endAt);else timers.push(setTimeout(()=>{if(token===playToken)stopPlayback()},Math.max(0,(endAt-audioContext.currentTime)*1000)+50))},Math.max(0,(endAt-audioContext.currentTime)*1000-300)))}
async function beginPlayback(){if(isPlaying){stopPlayback();return}if(!state.progression.length)return;try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();stopPlayback();const master=audioContext.createGain();master.connect(audioContext.destination);activeMasters.push(master);isPlaying=true;$('play').textContent='■ Detener';setStatus(`Reproduciendo a ${state.bpm} BPM${state.loop?' en bucle':''}.`);playCycle(playToken,audioContext.currentTime+.08)}catch(error){console.error('Fallo de reproducción:',error);stopPlayback();setStatus('El navegador no pudo reproducir el audio.',true)}}
async function audition(option){try{stopPlayback();audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const c=describe(option),upper=voiceChord(c,null),master=audioContext.createGain();master.connect(audioContext.destination);activeMasters.push(master);scheduleChord({...c,upper,bass:48+notePc(c.root)},audioContext.currentTime+.03,1.1,master);setStatus(`Escuchando ${c.name}: ${c.tones.join(' · ')}.`)}catch{setStatus('No se pudo escuchar este acorde.',true)}}
async function auditionGroove(row){if(!GROOVE_ROWS.includes(row))return;try{stopPlayback();audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const master=audioContext.createGain(),when=audioContext.currentTime+.03;master.connect(audioContext.destination);activeMasters.push(master);if(row==='bass'){const bass=voiceSequence()[0]?.bass??48;scheduleBassStep(bass,when,.18,master)}else scheduleDrum(row,when,master);setStatus(`Probando ${GROOVE_LABELS[row].toLowerCase()} · sonido ${SOUND_KITS[state.soundKit].name}.`)}catch(error){console.error('Fallo de preescucha:',error);setStatus('No se pudo probar este sonido.',true)}}
function variableLength(value){let buffer=value&0x7f,bytes=[];while((value>>=7)>0){buffer<<=8;buffer|=(value&0x7f)|0x80}for(;;){bytes.push(buffer&0xff);if(buffer&0x80)buffer>>=8;else break}return bytes}
function chunk(label,data){const size=data.length;return[...label.split('').map(ch=>ch.charCodeAt(0)),(size>>>24)&255,(size>>>16)&255,(size>>>8)&255,size&255,...data]}
function midiTrack(name,events,endTick){const label=[...name].map(char=>char.charCodeAt(0)),items=[{tick:0,order:0,data:[0xff,0x03,...variableLength(label.length),...label]},...events,{tick:endTick,order:4,data:[0xff,0x2f,0]}];items.sort((a,b)=>a.tick-b.tick||a.order-b.order);let previous=0;const bytes=[];items.forEach(item=>{bytes.push(...variableLength(item.tick-previous),...item.data);previous=item.tick});return chunk('MTrk',bytes)}
function midiBytes(part='all'){
  const ppq=480,tempo=Math.round(60000000/state.bpm),meta=[{tick:0,order:1,data:[0xff,0x51,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255]},{tick:0,order:1,data:[0xff,0x58,4,4,2,24,8]}],chords=[{tick:0,order:1,data:[0xc0,0]}],bass=[{tick:0,order:1,data:[0xc1,32]}],drums=[];
  let tick=0;const voiced=voiceSequence();voiced.forEach(c=>{const duration=c.beats*ppq,end=tick+Math.max(1,Math.round(duration*.9));if(!state.bassSteps)bass.push({tick,order:2,data:[0x91,c.bass,78]},{tick:end,order:1,data:[0x81,c.bass,0]});c.upper.forEach(n=>{chords.push({tick,order:2,data:[0x90,n,72]},{tick:end,order:1,data:[0x80,n,0]})});tick+=duration});
  grooveEvents(voiced).forEach(event=>{const at=Math.round(event.beat*ppq);if(event.row==='bass'){const off=at+Math.max(1,Math.round(event.duration*ppq));bass.push({tick:at,order:2,data:[0x91,event.note,82]},{tick:off,order:1,data:[0x81,event.note,0]})}else{const note={kick:36,clap:38,hat:42}[event.row],off=at+Math.round((event.row==='hat'?.12:.2)*ppq);drums.push({tick:at,order:2,data:[0x99,note,94]},{tick:off,order:1,data:[0x89,note,0]})}});
  tick+=paddingBeats()*ppq;const tracks=[midiTrack('Tempo',meta,tick)];if(part==='all'||part==='chords')tracks.push(midiTrack('Acordes',chords,tick));if(part==='all'||part==='bass')tracks.push(midiTrack('Bajo',bass,tick));if((part==='all'&&state.drumsEnabled)||part==='drums')tracks.push(midiTrack('Bateria',drums,tick));return new Uint8Array([...chunk('MThd',[0,1,0,tracks.length,1,224]),...tracks.flat()])
}
function exportMidi(){if(!state.progression.length)return;try{const part=$('midiPart').value,blob=new Blob([midiBytes(part)],{type:'audio/midi'}),objectUrl=URL.createObjectURL(blob),link=document.createElement('a');link.href=objectUrl;const tonic=root().replace('♯','#').replace('♭','b')+(state.mode==='minor'?'m':'');link.download=`progresion-${tonic}-${state.bpm}bpm${part==='all'?'':part==='bass'?'-bajo':part==='drums'?'-bateria':'-acordes'}.mid`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),30000);setStatus(part==='all'?`MIDI exportado en pistas separadas de acordes, bajo${state.drumsEnabled?' y batería':''}.`:`MIDI de ${{bass:'bajo',chords:'acordes',drums:'batería'}[part]} exportado.`)}catch(error){console.error('Fallo de exportación MIDI:',error);setStatus('No se pudo exportar el MIDI.',true)}}
function bindEvents(){
  $('keySelect').addEventListener('change',e=>changeKey(e.target.value,state.mode));
  $('modeSelect').addEventListener('change',e=>changeKey(parallelKey(e.target.value),e.target.value));
  $('relativeKey').addEventListener('click',()=>changeKey(state.key,state.mode==='major'?'minor':'major'));
  $('styleSelect').addEventListener('change',renderStyleInfo);
  $('applyStyle').addEventListener('click',applyStyle);
  $('groovePreset').addEventListener('change',e=>{const name=e.target.value;if(!GROOVE_PRESETS[name])return;stopPlayback();checkpoint();state.groove=presetGroove(name);if(name!=='empty'){state.soundKit=name;state.drumsEnabled=true;state.bassSteps=true}persist();renderGroove();e.target.value='';setStatus(name==='empty'?'Patrón limpiado; el sonido elegido se conserva.':`Patrón y sonido ${SOUND_KITS[state.soundKit].name} cargados; puedes editar cada paso.`)});
  $('soundKit').addEventListener('change',e=>{const name=kitName(e.target.value);if(name===state.soundKit)return;stopPlayback();checkpoint();state.soundKit=name;persist();renderGroove();setStatus(`Sonido ${SOUND_KITS[name].name} activado sin cambiar el patrón.`)});
  $('drumsEnabled').addEventListener('change',e=>{stopPlayback();checkpoint();state.drumsEnabled=e.target.checked;persist();renderGroove();setStatus(state.drumsEnabled?'Batería activada.':'Batería silenciada; el patrón sigue guardado.')});
  $('bassSteps').addEventListener('change',e=>{stopPlayback();checkpoint();state.bassSteps=e.target.checked;persist();renderGroove();setStatus(state.bassSteps?'Bajo por pasos activado.':'Bajo sostenido activado.')});
  $('grooveGrid').addEventListener('click',e=>{const preview=e.target.closest('[data-preview]');if(preview){auditionGroove(preview.dataset.preview);return}const cell=e.target.closest('[data-row][data-step]');if(!cell)return;const row=cell.dataset.row,step=Number(cell.dataset.step);if(!GROOVE_ROWS.includes(row)||!Number.isInteger(step)||step<0||step>15)return;stopPlayback();checkpoint();state.groove[row][step]=row==='bass'?(state.groove[row][step]+1)%4:1-state.groove[row][step];persist();renderGroove();setStatus(`${GROOVE_LABELS[row]}, paso ${step+1}: ${row==='bass'?['silencio','raíz','quinta','octava'][state.groove[row][step]]:state.groove[row][step]?'activo':'silencio'}.`)});
  $('extensionTriad').addEventListener('click',()=>{if(state.extension==='triad')return;checkpoint();state.extension='triad';persist();render()});
  $('extensionSeventh').addEventListener('click',()=>{if(state.extension==='seventh')return;checkpoint();state.extension='seventh';persist();render()});
  $('composerChords').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),preview=e.target.closest('[data-audition]'),options=chordOptions();if(add)addChord(options[Number(add.dataset.add)]);if(preview)audition(options[Number(preview.dataset.audition)])});
  $('progressGrid').addEventListener('click',e=>{const slot=e.target.closest('[data-slot]');if(slot)selectSlot(Number(slot.dataset.slot))});
  $('bpm').addEventListener('change',e=>{const bpm=Math.min(240,Math.max(40,Math.round(Number(e.target.value)||100)));if(bpm!==state.bpm){stopPlayback();checkpoint();state.bpm=bpm;persist()}render()});
  $('voicing').addEventListener('change',e=>{const value=e.target.value==='root'?'root':'smooth';if(value===state.voicing)return;stopPlayback();checkpoint();state.voicing=value;persist();render();setStatus(value==='smooth'?'Voces cercanas activadas.':'Posición fundamental activada.')});
  $('loop').addEventListener('change',e=>{checkpoint();state.loop=e.target.checked;persist();renderProgression();setStatus(state.loop?'Repetición activada.':'Repetición desactivada.')});
  $('alignBars').addEventListener('change',e=>{stopPlayback();checkpoint();state.alignBars=e.target.checked;persist();renderProgression();setStatus(state.alignBars?'El loop se alinea al siguiente compás.':'Loop libre activado; comprueba su longitud.')});
  $('beats').addEventListener('change',e=>{const value=Number(e.target.value);if(![1,2,4,8].includes(value))return;if(state.selected!==null&&state.progression[state.selected])changeProgression(()=>{state.progression[state.selected].beats=value});else{checkpoint();state.defaultBeats=value;persist();renderProgression()}});
  $('moveLeft').addEventListener('click',()=>moveSelected(-1));$('moveRight').addEventListener('click',()=>moveSelected(1));$('removeChord').addEventListener('click',removeSelected);
  $('clear').addEventListener('click',()=>{if(!state.progression.length)return;backupDraft();changeProgression(()=>{state.progression=[];state.selected=null});setStatus('Secuencia limpiada. Puedes recuperar el borrador anterior.')});
  $('undo').addEventListener('click',()=>{if(!undoStack.length)return;stopPlayback();restoreProject(undoStack.pop());persist();render();setStatus('Último cambio deshecho; proyecto completo restaurado.')});
  $('preset').addEventListener('click',()=>{const degrees=state.mode==='major'?[0,4,5,3]:[0,5,2,6],kind=state.extension;backupDraft();changeProgression(()=>{state.progression=degrees.map(degree=>({degree,kind,beats:4}));state.selected=null});setStatus('Progresión de ejemplo cargada. El borrador anterior se puede recuperar.')});
  $('play').addEventListener('click',beginPlayback);$('exportMidi').addEventListener('click',exportMidi);
  $('saveIdea').addEventListener('click',saveIdea);$('ideaName').addEventListener('keydown',e=>{if(e.key==='Enter')saveIdea()});$('loadIdea').addEventListener('click',loadIdea);$('deleteIdea').addEventListener('click',deleteIdea);$('recoverDraft').addEventListener('click',recoverDraft);
}
function bindWorkflowSteps(){
  const links=[...document.querySelectorAll('.workflow-steps a')];
  if(!links.length)return;
  const activate=link=>{links.forEach(item=>item.removeAttribute('aria-current'));link.setAttribute('aria-current','step')};
  links.forEach(link=>link.addEventListener('click',()=>activate(link)));
  const current=links.find(link=>link.hash===location.hash);
  if(current)activate(current);
}
bindWorkflowSteps();bindEvents();render();persist();
